remote_theme: just-the-docs/just-the-docs
title: WaveVortexModel
description: Solve the stratified nonhydrostatic equations of motion and decompose into wave-vortex components
compress_html:
  blanklines: true
